docs/AboutUs.md
docs/team/wei-song1.md

Update about us

---

docs/DeveloperGuide.md
docs/diagrams/ArchitectureSequenceDiagram.puml
src/main/java/seedu/address/MainApp.java
src/main/java/seedu/address/logic/Logic.java
src/main/java/seedu/address/logic/commands/ClearCommand.java
src/main/java/seedu/address/model/FinClient.java
src/main/java/seedu/address/model/Model.java
src/main/java/seedu/address/model/ModelManager.java
src/main/java/seedu/address/model/util/SampleDataUtil.java
src/main/java/seedu/address/storage/AddressBookStorage.java
src/main/java/seedu/address/storage/JsonAddressBookStorage.java
src/main/java/seedu/address/storage/JsonSerializableAddressBook.java
src/main/java/seedu/address/storage/StorageManager.java
src/main/java/seedu/address/ui/PersonCard.java
src/test/java/seedu/address/logic/commands/AddCommandTest.java
src/test/java/seedu/address/logic/commands/ClearCommandTest.java
src/test/java/seedu/address/logic/commands/CommandTestUtil.java
src/test/java/seedu/address/logic/commands/EditCommandTest.java
src/test/java/seedu/address/logic/parser/FinClientParserTest.java
src/test/java/seedu/address/model/FinClientTest.java
src/test/java/seedu/address/model/ModelManagerTest.java
src/test/java/seedu/address/storage/JsonFinClientStorageTest.java
src/test/java/seedu/address/storage/JsonSerializableFinClientTest.java
src/test/java/seedu/address/storage/StorageManagerTest.java
src/test/java/seedu/address/testutil/AddressBookBuilder.java
src/test/java/seedu/address/testutil/TypicalPersons.java

Modify DeveloperGuide.md and rename everything to FinClient

---

build.gradle

Fix gradle file so ./gradlew run works

---

build.gradle
src/main/java/seedu/finclient/logic/commands/SortCommand.java
src/test/java/seedu/finclient/logic/commands/SortCommandTest.java

Add sort feature

---

src/main/java/seedu/finclient/logic/commands/AddCommand.java
src/main/java/seedu/finclient/logic/commands/EditCommand.java
src/main/java/seedu/finclient/logic/parser/AddCommandParser.java
src/main/java/seedu/finclient/logic/parser/EditCommandParser.java
src/main/java/seedu/finclient/logic/parser/ParserUtil.java
src/main/java/seedu/finclient/model/person/Person.java
src/test/java/seedu/finclient/logic/LogicManagerTest.java
src/test/java/seedu/finclient/logic/commands/CommandTestUtil.java
src/test/java/seedu/finclient/logic/commands/EditPersonDescriptorTest.java
src/test/java/seedu/finclient/logic/parser/AddCommandParserTest.java

add: support remark input in AddCommand and Editcommand

---

src/test/java/seedu/finclient/model/person/PersonTest.java
src/test/java/seedu/finclient/testutil/TypicalPersons.java

Add more tests for phone numbers

---

build.gradle
src/main/java/seedu/finclient/ui/HelpWindow.java
src/main/resources/view/HelpWindow.css

Update HelpWindow UI color

---

build.gradle
src/main/java/seedu/finclient/ui/HelpWindow.java

Update HelpWindow file

---

src/main/java/seedu/finclient/model/person/Person.java
src/test/java/seedu/finclient/model/person/PersonTest.java

fix: update hide function to work with remarks

---

src/main/java/seedu/finclient/logic/parser/AddCommandParser.java
src/main/java/seedu/finclient/storage/JsonAdaptedPerson.java
src/main/java/seedu/finclient/ui/PersonCard.java

Make remark optional

---

src/main/java/seedu/finclient/logic/commands/ExitCommand.java
src/main/java/seedu/finclient/ui/HelpWindow.java
src/main/java/seedu/finclient/ui/MainWindow.java
src/main/resources/view/DarkTheme.css
src/main/resources/view/MainWindow.fxml
src/main/resources/view/PersonListCard.fxml
src/main/resources/view/ResultDisplay.fxml

Allow for exit with shortcut
Update GUI components
Fix #80

Update GUI and add shortcuts

---

src/main/java/seedu/finclient/ui/HelpWindow.java
src/main/resources/view/DarkTheme.css
src/main/resources/view/HelpWindow.css
src/main/resources/view/HelpWindow.fxml
src/main/resources/view/MainWindow.fxml
src/main/resources/view/PersonListCard.fxml
src/main/resources/view/ResultDisplay.fxml
src/test/java/seedu/finclient/ui/HelpWindowTest.java

Update Help message
Update HelpWindow dimension
Add border in PersonCard

Update GUI component

---

src/main/java/seedu/finclient/ui/PersonCard.java

For parallel PR, dont merge yet

Remove debugging message

---

src/main/java/seedu/finclient/logic/Logic.java
src/main/java/seedu/finclient/logic/LogicManager.java
src/main/java/seedu/finclient/model/FinClient.java
src/main/java/seedu/finclient/model/Model.java
src/main/java/seedu/finclient/model/ModelManager.java
src/main/java/seedu/finclient/model/person/Remark.java
src/main/java/seedu/finclient/model/person/UniquePersonList.java
src/main/java/seedu/finclient/ui/MainWindow.java
src/main/java/seedu/finclient/ui/UpcomingEventsPanel.java
src/main/resources/view/DarkTheme.css
src/main/resources/view/MainWindow.fxml
src/main/resources/view/UpcomingEventsPanel.fxml
src/test/java/seedu/finclient/logic/commands/AddCommandTest.java
src/test/java/seedu/finclient/logic/commands/HideCommandTest.java
src/test/java/seedu/finclient/logic/commands/OrderCommandTest.java
src/test/java/seedu/finclient/logic/commands/RevealCommandTest.java
src/test/java/seedu/finclient/model/person/UniquePersonListTest.java
src/test/java/seedu/finclient/ui/UpcomingEventsPanelTest.java

Add reminder interface

---

src/main/java/seedu/finclient/ui/MainWindow.java
src/main/java/seedu/finclient/ui/PersonCard.java
src/main/java/seedu/finclient/ui/UpcomingEventsPanel.java
src/main/resources/view/MainWindow.fxml
src/main/resources/view/PersonListCard.fxml
src/main/resources/view/UpcomingEventsPanel.fxml

Fix #127 
Fix #128 
Fix #132 
Fix #142

Fix GUI resizing and overflow scaling issues

---

docs/UserGuide.md
src/main/java/seedu/finclient/logic/commands/SortCommand.java
src/main/java/seedu/finclient/model/order/Order.java
src/main/java/seedu/finclient/model/person/Person.java
src/main/java/seedu/finclient/model/person/Remark.java
src/test/java/seedu/finclient/logic/commands/CommandTestUtil.java
src/test/java/seedu/finclient/model/order/OrderTest.java
src/test/java/seedu/finclient/model/person/PersonTest.java
src/test/java/seedu/finclient/model/person/RemarkTest.java
src/test/java/seedu/finclient/model/person/UniquePersonListTest.java
src/test/java/seedu/finclient/testutil/TypicalPersons.java

Fixes #137  Now when sort by price/amount, sell and buy orders are separated.

Fix the bug of sort order

---

src/test/java/seedu/finclient/model/person/PersonTest.java

This ensures our coverage is maintained. 
Fixes #136

Add more test cases to PersonTest.java

---

src/main/java/seedu/finclient/logic/parser/ParserUtil.java
src/main/java/seedu/finclient/model/order/CallAuctionCalculator.java
src/main/java/seedu/finclient/model/order/Order.java
src/test/java/seedu/finclient/model/order/OrderTest.java

fix #141 
Note that there will definitely be an upper bound of amount and here we follow conventions to use long(64-bit integer).

fix: update order's quantity field to 64-bit long integer

---

docs/DeveloperGuide.md
docs/UserGuide.md
docs/diagrams/ModelClassDiagram.puml

Fix #255
Fix #254
Fix #253
Fix #252
Fix #250
Fix #248
Fix #247
Fix #246
Fix #245
Fix #244
Fix #242
Fix #240
Fix #237
Fix #236
Fix #234
Fix #233
Fix #232
Fix #231
Fix #228
Fix #225
Fix #222
Fix #210
Fix #208
Fix #206
Fix #205
Fix #203
Fix #202
Fix #192

Fix Documentation Bugs from PE-D

---

docs/UserGuide.md
src/main/java/seedu/finclient/model/person/Name.java
src/main/java/seedu/finclient/model/person/Person.java
src/test/data/JsonSerializableFinClientTest/duplicatePersonFinClient.json
src/test/java/seedu/finclient/model/FinClientTest.java
src/test/java/seedu/finclient/model/person/NameTest.java
src/test/java/seedu/finclient/model/person/PersonTest.java
src/test/java/seedu/finclient/model/person/UniquePersonListTest.java

Fix PE-D Bugs

---

src/main/java/seedu/finclient/model/person/Address.java
src/test/java/seedu/finclient/model/person/AddressTest.java

Fixes #251

---

docs/DeveloperGuide.md

Fix #215 
Fix #212
Fix #201 
Fix #193

Update Developer Guide with Planned Enhancements

---

docs/UserGuide.md
docs/diagrams/UndoRedoState0.puml
docs/diagrams/UndoRedoState1.puml
docs/diagrams/UndoRedoState2.puml
docs/diagrams/UndoRedoState3.puml
docs/diagrams/UndoRedoState4.puml
docs/diagrams/UndoRedoState5.puml
docs/diagrams/UndoSequenceDiagram-Logic.puml
docs/diagrams/UndoSequenceDiagram-Model.puml

Make sure the names of the product is consistent

Update Developer Guide

---

docs/DeveloperGuide.md
docs/diagrams/BetterModelClassDiagram.puml
docs/diagrams/ModelClassDiagram.puml
src/main/java/seedu/finclient/logic/commands/SortCommand.java
src/main/java/seedu/finclient/model/person/Person.java
src/main/java/seedu/finclient/ui/HelpWindow.java
src/main/java/seedu/finclient/ui/UpcomingEventsPanel.java
src/test/java/seedu/finclient/model/person/PersonTest.java
src/test/java/seedu/finclient/model/person/RemarkTest.java
src/test/java/seedu/finclient/model/person/UniquePersonListTest.java

Make the functional code consistent

Change all deadline into timestamp

---

docs/DeveloperGuide.md

For participation

---

docs/UserGuide.md

Update the help message image in the User Guide

Change help message image
